version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rtscts123
      MYSQL_DATABASE: legend_of_the_yellow_dragon
      MYSQL_USER: yellow_dragon_admin
      MYSQL_PASSWORD: YellowDragonAdmin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    image: tomcat:9.0
    container_name: spring-tomcat
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - E:\IDEs\Intellij Repositories\Legend-of-the-yellow-Dragon\:/usr/local/tomcat/webapps:ro
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data: