playerClass.warrior.name=Krieger
playerClass.warrior.description=Krieger sind zähe Kämpfer. Ihre rohe Stärke und hohe Vitalität machen sie zu schwer bezwingbaren Gegner. \
  Sie stehen noch lange nachdem andere schon längst zu boden gegangen wären.
playerClass.warrior.positives=Erhält zusätzlich 10% - 30% Lebenspunkte
playerClass.warrior.negatives=Angriffe verbrauchen zusätzlich 10% mehr Ausdauer
playerClass.mage.name=Zauberer
playerClass.mage.description=Magier sind sehr Intelligente Kämpfer. Sie sind äusserst Trickreich und können mit mächtigen Zaubern das Geschick des Kampfes für sich entscheiden
playerClass.mage.positives=Erhält die Ressource Mana und Zaubersprüche die sie im Kampf einsetzen können
playerClass.mage.negatives=Not Implemented yet
playerClass.duelist.name=Duellist
playerClass.duelist.description=Duellisten sind für ihre übernatürliche Agilität bekannt. Sie können ihre Gegner geschickt ausmanövrieren und gezielt Schwachstellen angreifen.
playerClass.duelist.positives=Erhält einen Bonus von 10% - 30% auf Rüstungsdurchdringung in Abhängigkeit vom Charakter Level
playerClass.duelist.negatives=Schadenreduktion von Rüstung ist um 20% geringer
playerClass.monk.name=Mönch
playerClass.monk.description=Mönche sind ausgeglichene Kämpfer. Sie legen großen Wert auf Gleichgewicht zwischen Körper ung Geist. Sie sind dadurch im stetigen Einklang mit sich selbst und der Welt um sich herum.
playerClass.monk.positives=Beim Levelaufstieg werden alle Attribute erhöht
playerClass.monk.negatives=Bekommt nur einen Attributs punkt bei einem Level up