sidebar.headline.administration=<b>Administration</b>
sidebar.headline.character=<b>Charakter</b>
sidebar.items=Items
sidebar.user=Nutzer
sidebar.character=Charakter
sidebar.character.create=Neuen Charakter erstellen
sidebar.character.edit=Charakter bearbeiten
sidebar.home=Übersicht
sidebar.characterAdministration=Charakter Verwaltung
#___CharacterSelection___
characterSelection.card.button.select=Auswählen
characterCreation.introduction=Willkommen am Tempel der Ewigkeit! Beschwöre deinen Charakter und gib ihm die Form die er für euer Abenteuer haben soll.
characterCreation.nameSelect=Wähle den Namen deines Charakters.
characterCreation.pointDisplay.withPlaceholder=Verfügbare Punkte : #
characterCreation.description.attributes=Verteile nun deine Attributspunkte
characterCreation.description.playerClass=Wähle nun deine Klasse.\nDeine Klasse hat Auswirkungen auf deine generellen Werte.
characterCreation.button.submit=Erschaffe deinen Charakter
#___Registration___
registration.greeting=Willkommen Reisender
registration.greetingText=Bereite dich auf eine epische Reise in eine Welt voller Magie und Abenteuer vor! Registriere dich jetzt, beschwöre deine Charaktere und stürz dich ins Getümmel! Durch ein magisches Ereignis von ungeahntem Ausmaß wurde die\
  Realität in ihren Grundfesten erschüttert. Viele Reiche aus vielen Dimensionen wild zusammen gewürfelt. Verwirrung, Misstrauen und Angst sind allgegenwärtig. Sie brauchen jemand der ihnen Hoffnung gibt!
logout.goodbye=Ruh dich aus erschöpfte/r Kämpfer/in. Es liegt ein Tag voller Anstrengung und Entbehrung hinter dir und es wird nicht der letzte sein.
#___Tavern___
tavern.description=Willkommen in der Taverne.\n Der Ort an dem müde Abenteurer sich ausruhen und wieder zu kräften kommen können.\n Ein warmes Bett kombiniert mit einer warmen Mahlzeit haben noch jede Erschöpfung beseitigt\
  \n \n Füllt nach einer Rast euer Leben vollständig auf.
tavern.restButton=Rasten({0}G)
#___Dashboard___
dashboard.description=Im Arbeitszimmer erwartet euch eine vielzahl von Pergamenten, Büchern und anderen Schriftstücken. Ihr späht über euren Schreibtisch, ob ihr etwas Neues erspähen könnt.
dashboard.description.noMessages=Doch keine neuen Schriftstücke die euere Aufmerksamkeit erfordern