spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=false
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
spring.config.import=optional:file:${user.dir}/.env[.properties]
#Kompletes Logging umstellen
#logging.level.root=debug
#Klassensprezifisches Logging umstellen
#logging.level.RegistrationDTOConstraintValidator=DEBUG
#Thymeleaf Logging
#logging.level.org.thymeleaf=DEBUG
#logging.level.org.attoparser=DEBUG
#logging.level.nz.net.ultra.thymeleaf=DEBUG
#logging.level.de.game.service.SettingService=DEBUG
#Logging um zu sehen ob Post von React am Server ankommt und abgewiesen wird
#logging.level.org.springframework.security=DEBUG