spring.application.name=Legend-of-the-yellow-Dragon
application.custom.default.adminAccountPrefix=ad_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mandatory-file-encoding=UTF-8
spring.messages.basename=lang/messages,lang/errors,lang/sites,lang/labels
logging.level.org.hibernate=warn
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.orm.jdbc.bind=off
server.port=8081
